on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Remove File
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./dist/win-unpacked
      - name: Push to built branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: downloads # The branch name where you want to push the assets
          FOLDER: dist # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}